#!/bin/bash

export FLASK_ENV=development
. venv/bin/activate
inotifywait -rme modify . @*.swp | while read line; do 
	echo "$line"; 
	kill $FLASKPID; 
	clear;
	flask run & FLASKPID=$!; 
	echo $FLASKPID; 
done
